### ISSUE TITLE
Smartblock trigger

### ISSUE THREAD

**Issue by Egger1513** [kdnk/roamist#37]
Hi kdnk,
Non-coder here, so please excuse my ignorance. I love what you have built here and I am very keen to incorporate it into my workflow.
I have successfully setup Roamist within my Roam graph. I believe that I have configured it correctly, but I am sure I will be able to figure that out.
My challenge is with the smartblocks. I already run smartblocks for a number of different things in my graph. In this case, it isn't clear to me how to create the relevant smartblock that will run the process of importing Todoist tasks into Roam.
In your CleanShot I can see that you have 3 smartblocks setup from which to choose which process to run. Could you perhaps help me out by letting me know what these should consist of i.e. what should be nested under each smartblock in order to trigger the process?

**Comment by kdnk** [comment]
@Egger1513
Sorry for the inconvenience. ~~I know this readme is not sufficient, so I'll update it soon.~~
Are you talking about this screenshot? https://github.com/kdnk/roamist#pull-tasks

To import tasks from Todoist, you need to configure Todoist's filter on `[[roam/roamist]]` page.
- The first block
  - it should be literally `filters`. (I want to improve it, but I don't have good ideas for now.)
- The second block
  - it is the names of your filter. You can use anything you want.
- The third block 
  - it is Todoist's filter. You can make it with reference to https://todoist.com/help/articles/introduction-to-filters.

This is a minimum config you can try.
```
- filters
   - today
       - today
```

<details>

<summary>ref. my filters</summary>

```
-  filters
    - work
        - #🔨Work & today & !@waiting
    - daily
        - (!#🔨Work & !#Inbox & !#Quick Capture & !#🧘Routine & !#🦒Personal) & today
```

</details>


After setting these up, you need to reload your Roam.
Then some smart blocks will be automatically added under `workflows` block on `[[roam/roamist]]`, and you should be able to run smart blocks to import Todoist's tasks.


Feel free to ask me anything if you still have some questions.

**Comment by kdnk** [comment]
@Egger1513
I've updated README https://github.com/kdnk/roamist#setup, so please refer to this if you have some problems.

**Comment by Egger1513** [comment]
Hi

It is no inconvenience. Thank you for your quick response.

I have been able to resolve the issue with regards to the smartblocks, and those are now generating correctly based on what I enter in the configuration.

I am currently not yet able to import the Todoist task when running the smartblock, and I suspect it might have something to do with my filters.

The below is a screenshot of my Todoist filter (Filter name and Filter query):


I have therefore done the configuration as follows:



I was unsure if I should be using the Todoist filter name or the filter query in the third block. I have however tried it for both but have not yet been able to import. Is there perhaps something you can see that I am doing wrong?

Regards

**Comment by Egger1513** [comment]
Update:

After I sent my previous response, I tried the minimum config option you suggested and managed to import the tasks from Todoist into Roam. Your tool therefore works exactly as you described, and I suspect it is rather me that just needs to adjust my Todoist filters.

**Comment by kdnk** [comment]
@Egger1513 

The third one should be a query of Todoist's filter.
FYI: This is my config.

```
-  filters
    - work
        - #🔨Work & today & !@waiting
    - daily
        - (!#🔨Work & !#Inbox & !#Quick Capture & !#🧘Routine & !#🦒Personal) & today
```

If you couldn't get any tasks, you might misconfigure something with your Todoist's query.
I recommend you check it on Todoist before configuring it on Roam.

**Comment by kdnk** [comment]
@Egger1513 Could you make this work as expected? I'll close this issue, but feel free to open this if you still have some problems.
