### ISSUE TITLE
Logseq support

### ISSUE THREAD

**Issue by krillin666** [kdnk/roamist#72]
Hey there @kdnk , amazing plugin you're writing here !

I wanted to challenge you to shift your focus onto writing this to Logseq which is open source but has the benefit of automatically assigning an ID to each block.
Some ideas this could work over at logseq: 

You can assign it via page properties or alternatively track the UUID you just have to make sure to persist it via the logseq.editor.upsertBlockProperty api.
And I believe most apis give a specific block if
You just need to store a dictionary somewhere of the blocks and their corresponding uuids.
You can either store it in settings or using the file system api to save a json or something

**Comment by kdnk** [comment]
I've tried Logseq some times, and feels promising. But I'm not going to use it instead of Roam at this time, because it looks like lacking a file syncing feature.
Roamist uses `@doist/todoist-api-typescript`, so you might refer to some codes when you create Logseq plugin on your own.

**Comment by krillin666** [comment]
Completely understand :smile: 

Logseq will have a file sync feature in the near future, but you can sync now with GIT or Syncthing !

**Comment by kdnk** [comment]
> but you can sync now with GIT or Syncthing !

I know Logseq has that kind of feature, but I don't want to use extra tools...

> Logseq will have a file sync feature in the near future, 

Yeah, I'm looking forward to using this feature, and if I switched to Logseq thanks to this feature, I would make Todoist integration for Logseq.
