### ISSUE TITLE
Todoist priority preference

### ISSUE THREAD

**Issue by Egger1513** [kdnk/roamist#79]
## Why
When using Todoist mainly as the capturing tool, and then managing tasks within Roam, the task priority assigned in Todoist could become unnecessary in certain workflows. This is also due to not being able to sync changes to priorities between the platforms once the task has been created in Roam. Having the option to include/exclude the Todoist assigned priority would serve to tidy things up for those not using it, ensuring process efficiency of the workflow.

## What
Consider creating a selectable option within the configuration page that allows one to enable/disable the importation of Todoist assigned priorities.
Priorities cannot not be disabled in Todoist, but perhaps, the data to be imported into Roam can be optionally selective?

**Comment by kdnk** [comment]
@Egger1513 I implemented `Hide priority` option, so please give it a try.
If you have some feature requests, feel free to open a new issue. Thanks for your feedback!

![CleanShot 2022-05-28 at 19 32 34](https://user-images.githubusercontent.com/15260226/170821604-6113a59f-c18c-4cf5-9205-f2c67a56429c.png)

**Comment by Egger1513** [comment]
Works perfectly. Thank you very much!
